### PR TITLE
Add trakt.tv provider

### PR DESCRIPTION
**Pull request by coolmule0**
Creates Items when completed a watch of a film or show, if registered at trakt.tv.

Issues: 
 - [ ] Has dependency on `arrow`, which conflicts with the ics library. Ideally the ics package can be updated to be more permissable for the `arrow` depencency.

### CODE REVIEW

**Comment by jakubvalenta** [comment]
Thanks for the PR! I will look into it on the weekend.

**Comment by jakubvalenta** [comment]
I've upgraded the project to use poetry instead of Pipenv. That allows us to install `ics` 0.8.0-dev, which doesn't depend on `arrow`. So now it should be possible to install both `ics` and `trakt.py`. Can you please rebase your PR onto `master` and add the `trakt.py` dependency in `pyproject.toml` (since `Pipfile` has been deleted)?

Second: please run `make reformat` to automatically adjust code style of the new files.

Then I'd be happy to merge your PR. I haven't tested the provider myself, because I don't use trakt, but the code looks really good!

**Comment by coolmule0** [comment]
Completed those those steps now

**Comment by jakubvalenta** [comment]
Thank you

**Pull request merged**
